### PR TITLE
Fix/windows issues

### PR DESCRIPTION
**Pull request by AndyMik90**
## Base Branch

- [ ] This PR targets the `develop` branch (required for all feature/fix PRs)
- [ ] This PR targets `main` (hotfix only - maintainers)

## Related Issue

Closes #

## Type of Change

- [ ] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 📚 Documentation
- [ ] ♻️ Refactor
- [ ] 🧪 Test

## Area

- [ ] Frontend
- [ ] Backend
- [ ] Fullstack

## Commit Message Format

Follow conventional commits: `<type>: <subject>`

**Types:** feat, fix, docs, style, refactor, test, chore

**Example:** `feat: add user authentication system`

## Checklist

- [ ] I've synced with `develop` branch
- [ ] I've tested my changes locally
- [ ] I've followed the code principles (SOLID, DRY, KISS)
- [ ] My PR is small and focused (< 400 lines ideally)

## CI/Testing Requirements

- [ ] All CI checks pass
- [ ] All existing tests pass
- [ ] New features include test coverage
- [ ] Bug fixes include regression tests

## Screenshots

| Before | After |
|--------|-------|
|        |       |

## Feature Toggle

- [ ] Behind localStorage flag: `use_feature_name`
- [ ] Behind settings toggle
- [ ] Behind environment variable/config
- [ ] N/A - Feature is complete and ready for all users

## Breaking Changes

**Breaking:** Yes / No

**Details:**

## Summary by CodeRabbit

* **New Features**
  * Ollama install detection and one-click install; onboarding updated with Ollama states
  * Project removal confirmation dialog
  * New IPC and API endpoints to check/install Ollama

* **Improvements**
  * Centralized plan-file persistence to keep UI and plan files in sync (safer, locked updates)
  * Better Windows terminal handling and command escaping; improved executable discovery and terminal launching
  * Targeted cleanup of bundled Python files to reduce installer size
  * Enhanced Ollama model selector with install/run state, progress, and badges

* **Refactor**
  * Project settings reorganized; Claude-related settings removed and split into focused sections

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Review by AndyMik90 — COMMENTED** [review]
## 🤖 Auto Claude PR Review

### Merge Verdict: 🟠 NEEDS REVISION
2 issue(s) must be addressed (1 required, 1 recommended), 4 suggestions

### Risk Assessment
| Factor | Level | Notes |
|--------|-------|-------|
| Complexity | Low | Based on lines changed |
| Security Impact | Medium | Based on security findings |
| Scope Coherence | Good | Based on structural review |

### Findings Summary
- **High**: 1 issue(s)
- **Medium**: 1 issue(s)
- **Low**: 4 issue(s)

---
_Generated by Auto Claude PR Review_

### Findings (6 selected of 6 total)

#### 🟠 [HIGH] Windows buildCdCommand vulnerable to command injection via metacharacters
📁 `apps/frontend/src/shared/utils/shell-escape.ts:56`

The new Windows-specific code in buildCdCommand only escapes double quotes with `path.replace(/"/g, '""')`, but does not escape cmd.exe metacharacters like &, |, <, >. A path containing '&malicious_command' would execute that command. The codebase already has escapeShellArgWindows() that properly escapes these characters, but it's not being used here.

**Suggested fix:**
```
Use the existing escapeShellArgWindows function: `const escaped = escapeShellArgWindows(path); return \`cd "${escaped}" && \`;` OR wrap the path with full escaping before quoting.
```

#### 🟡 [MEDIUM] Tab close behavior changed from close-tab to remove-project
📁 `apps/frontend/src/renderer/App.tsx:485`

The handleProjectTabClose function now calls removeProject(projectId) instead of closeProjectTab(projectId). This is a significant behavior change - closing a tab now removes the project entirely from the app (though files are preserved on disk). The comment indicates this is intentional, but users may expect 'close tab' to only hide the tab, not remove the project.

**Suggested fix:**
```
Verify this behavior change is intentional and documented. Consider adding a confirmation dialog when closing tabs, or rename the action to make it clear the project is being removed.
```

#### 🔵 [LOW] Extensive skipCommands list is intentional but should be documented
📁 `apps/frontend/src/renderer/components/terminal/useAutoNaming.ts:24`

The new skipCommands list includes 50+ common commands (git, npm, docker, python, etc.). This is intentional - these generic commands shouldn't trigger auto-naming since they don't represent specific tasks. However, the Gemini AI flagged this as HIGH priority. The implementation is correct: it compares the first word of the command (lowercase) against the skip list.

**Suggested fix:**
```
Add a comment explaining WHY these commands are skipped (they're too generic for meaningful terminal names). This addresses the Gemini concern and improves maintainability.
```

#### 🔵 [LOW] shell: true for .cmd/.bat validation is necessary but adds attack surface
📁 `apps/frontend/src/main/cli-tool-manager.ts:677`

The PR adds `shell: true` when validating Windows .cmd/.bat files with execFileSync. This is necessary because Windows .cmd files must run through cmd.exe. The risk is mitigated because: (1) claudeCmd comes from internal path detection, not direct user input, and (2) only '--version' argument is passed. However, if claudeCmd could ever be user-controlled, this would be a command injection vector.

**Suggested fix:**
```
No immediate fix needed, but add a comment noting that claudeCmd must come from trusted sources only. Consider using escapeShellArgWindows if the path origin ever changes.
```

#### 🔵 [LOW] EnvironmentSettings import may become unused after Claude section removal
📁 `apps/frontend/src/renderer/components/settings/sections/SectionRouter.tsx:5`

The PR removes the entire 'claude' case from SectionRouter, which was the only place using EnvironmentSettings. Verify the import is also removed or still used elsewhere to avoid dead code.

**Suggested fix:**
```
Check if EnvironmentSettings is used elsewhere after the 'claude' case removal. If not, remove the import statement.
```

#### 🔵 [LOW] Windows extension priority reorder is correct
📁 `apps/frontend/src/main/env-utils.ts:160`

The change from ['', '.exe', '.cmd', '.bat', '.ps1'] to ['.exe', '.cmd', '.bat', '.ps1', ''] is correct. On Windows, native executables (.exe, .cmd) should be found before extensionless files (which are typically bash/sh scripts for Git Bash/Cygwin). This prevents accidentally running Unix scripts when a native Windows executable exists.

**Suggested fix:**
```
No fix needed - this is a correct improvement.
```

---
*This review was generated by Auto Claude.*

**Review by AndyMik90 — COMMENTED** [review]
## 🤖 Auto Claude PR Review

## 🚫 Follow-up Review: Blocked

### Resolution Status
- ✅ **Resolved**: 3 previous findings addressed
- ❌ **Unresolved**: 2 previous findings remain
- 🆕 **New Issues**: 2 new findings in recent changes

### Verdict
BLOCKED due to unresolved CRITICAL build-breaking issue: SectionRouter.tsx (line 5) still imports EnvironmentSettings.tsx which the PR deletes. This file was NOT modified in commits 5234224 or aefb281. TypeScript compilation will fail immediately after merge with 'Cannot find module' error. While 3 of 5 previous findings were successfully resolved (shell escaping improvements, sync limitation documentation), the CRITICAL import issue must be fixed before merge. Additionally, a new MEDIUM severity UI regression was introduced (Retry button can be spam-clicked). The import fix is required to unblock.

### Review Process
Agents invoked: resolution-verifier, new-code-reviewer

---
*This is an AI-generated follow-up review using parallel specialist analysis.*


### Findings (4 selected of 4 total)

#### 🔴 [CRITICAL] [UNRESOLVED] [UNRESOLVED] Import references deleted file EnvironmentSettings.tsx
📁 `apps/frontend/src/renderer/components/settings/sections/SectionRouter.tsx:5`

SectionRouter.tsx imports EnvironmentSettings from a file that this PR deletes. The import at line 5 and usage at line 118 will cause TypeScript compilation to fail after merge. This file was not updated as part of the PR.

Resolution note: SectionRouter.tsx is NOT in the list of changed files (agent-events-handlers.ts, claude-code-handlers.ts, execution-handlers.ts, plan-file-utils.ts). The import statement at line 5 still references the deleted EnvironmentSettings.tsx file.

Resolution note: SectionRouter.tsx is NOT in the list of changed files since last review. The resolution-verifier confirmed the import at line 5 still references EnvironmentSettings from '../../project-settings/EnvironmentSettings' and is used at lines 118-130 in the 'claude' case. TypeScript compilation will fail after merge.

**Suggested fix:**
```
Update SectionRouter.tsx to remove the EnvironmentSettings import and the 'claude' case that uses it, or keep the EnvironmentSettings.tsx file.
```

#### 🔵 [LOW] [UNRESOLVED] [UNRESOLVED] [UNRESOLVED] EnvironmentSettings import may become unused after Claude section removal
📁 `apps/frontend/src/renderer/components/settings/sections/SectionRouter.tsx:5`

The PR removes the entire 'claude' case from SectionRouter, which was the only place using EnvironmentSettings. Verify the import is also removed or still used elsewhere to avoid dead code.

Resolution note: EnvironmentSettings.tsx is deleted by this PR (shown in diff), and the export from project-settings/index.ts is removed. However, SectionRouter.tsx (NOT in changed files list) still imports EnvironmentSettings at line 5 and uses it at line 118. This will cause TypeScript compilation failure after merge.

Resolution note: SectionRouter.tsx was not modified in this commit. The import of EnvironmentSettings and its usage in the 'claude' case remain unchanged.

Resolution note: The EnvironmentSettings import at line 5 of SectionRouter.tsx is still present and actively used. The 'claude' case was not removed from the switch statement.

**Suggested fix:**
```
Check if EnvironmentSettings is used elsewhere after the 'claude' case removal. If not, remove the import statement.
```

#### 🟡 [MEDIUM] UI regression: Retry button no longer disabled during loading
📁 `apps/frontend/src/renderer/components/onboarding/OllamaModelSelector.tsx:340`

The diff removed 'disabled={isLoading}' from the Retry button. Users can now spam-click the button while a check is already in progress, potentially causing race conditions or multiple concurrent API calls. The animate-spin class was also removed from RefreshCw icon, removing visual feedback.

**Suggested fix:**
```
Restore disabled={isLoading} prop on the Button and restore conditional spin: className={cn('h-3.5 w-3.5 mr-1.5', isLoading && 'animate-spin')}
```

#### 🔵 [LOW] Dead code: escape functions defined but never used
📁 `apps/frontend/src/main/ipc-handlers/claude-code-handlers.ts:95`

Both escapePowerShellCommand() and escapeGitBashCommand() are defined but never called. The actual install commands use hardcoded strings from getInstallCommand() without escaping. These functions add confusion about whether escaping is happening and may mislead future developers.

**Suggested fix:**
```
Either use the functions to escape command parameters, or remove them if not needed (since commands are hardcoded and safe).
```

---
*This review was generated by Auto Claude.*

**Comment by AndyMik90** [comment]
## ✅ Auto Claude PR Review - APPROVED

## ✅ Follow-up Review: Ready To Merge

### Resolution Status
- ✅ **Resolved**: 2 previous findings addressed
- ❌ **Unresolved**: 0 previous findings remain
- 🆕 **New Issues**: 1 new findings in recent changes

### Finding Validation
- 🔍 **Dismissed as False Positives**: 2 findings were re-investigated and found to be incorrect
- ✓ **Confirmed Valid**: 0 findings verified as genuine issues
- 👤 **Needs Human Review**: 0 findings require manual verification

### Verdict
Previous CRITICAL finding (NEW-005) and LOW finding (a2b049021cc4) were both DISMISSED as false positives with high confidence (0.95). The EnvironmentSettings.tsx file exists and is properly imported/used, and the 'claude' case exists in SectionRouter.tsx. The security fixes in this PR (shell injection prevention via execFileSync, TOCTOU fixes via try/catch patterns) are correctly implemented. Pre-existing issues in files outside this PR's scope (release-handlers.ts, oauth-handlers.ts) are not regressions and don't block merge. CodeRabbit's actionable comment is truncated but the security fixes follow correct patterns.

### Review Process
Agents invoked: resolution-verifier, new-code-reviewer, comment-analyzer, finding-validator

---
*This is an AI-generated follow-up review using parallel specialist analysis with finding validation.*


---
*This approval was generated by Auto Claude.*
